"""Add CandlestickImage for storing training image data

Revision ID: 357392df756f
Revises: 7f2a17a8564c
Create Date: 2024-06-08 00:59:23.988676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357392df756f'
down_revision: Union[str, None] = '7f2a17a8564c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candlestick_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candlestick_images')
    # ### end Alembic commands ###
