"""Add timestamp to models

Revision ID: 72e94839d9e3
Revises: d52098ef7a03
Create Date: 2024-06-12 10:15:17.611446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e94839d9e3'
down_revision: Union[str, None] = 'd52098ef7a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_frame_entries', sa.Column('timestamp', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_frame_entries', 'timestamp')
    # ### end Alembic commands ###
