"""Add timeframe column to MarketData

Revision ID: 7f2a17a8564c
Revises: 634258c57f3d
Create Date: 2024-06-01 11:27:19.798678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2a17a8564c'
down_revision: Union[str, None] = '634258c57f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('timeframe', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data', 'timeframe')
    # ### end Alembic commands ###
