"""add indexes

Revision ID: d52098ef7a03
Revises: 1f914517221a
Create Date: 2024-06-11 00:15:34.314282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52098ef7a03'
down_revision: Union[str, None] = '1f914517221a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candlestick_images', 'timestamp',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_candlestick_images_collection_name'), 'candlestick_images', ['collection_name'], unique=False)
    op.create_index('ix_candlestick_images_label', 'candlestick_images', ['label'], unique=False)
    op.create_index(op.f('ix_candlestick_images_timestamp'), 'candlestick_images', ['timestamp'], unique=False)
    op.create_index('ix_collections_collection_name', 'collections', ['collection_name'], unique=False)
    op.create_index(op.f('ix_data_frame_entries_data_frame_metadata_id'), 'data_frame_entries', ['data_frame_metadata_id'], unique=False)
    op.create_index('ix_data_frame_metadata_label', 'data_frame_metadata', ['label'], unique=False)
    op.create_index('ix_data_frame_metadata_timestamp', 'data_frame_metadata', ['timestamp'], unique=False)
    op.create_index('ix_market_data_symbol', 'market_data', ['symbol'], unique=False)
    op.create_index('ix_market_data_timeframe', 'market_data', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index('ix_market_data_timeframe', table_name='market_data')
    op.drop_index('ix_market_data_symbol', table_name='market_data')
    op.drop_index('ix_data_frame_metadata_timestamp', table_name='data_frame_metadata')
    op.drop_index('ix_data_frame_metadata_label', table_name='data_frame_metadata')
    op.drop_index(op.f('ix_data_frame_entries_data_frame_metadata_id'), table_name='data_frame_entries')
    op.drop_index('ix_collections_collection_name', table_name='collections')
    op.drop_index(op.f('ix_candlestick_images_timestamp'), table_name='candlestick_images')
    op.drop_index('ix_candlestick_images_label', table_name='candlestick_images')
    op.drop_index(op.f('ix_candlestick_images_collection_name'), table_name='candlestick_images')
    op.alter_column('candlestick_images', 'timestamp',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
