"""Update CandlestickImage to include label

Revision ID: f3ca02425119
Revises: 357392df756f
Create Date: 2024-06-08 01:09:13.682693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ca02425119'
down_revision: Union[str, None] = '357392df756f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candlestick_images', sa.Column('label', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candlestick_images', 'label')
    # ### end Alembic commands ###
